Add aioredis instrumentation
elastic/apm-agent-python pull request #1082
Opened 2021-03-29 07:01 UTC by Sparkycz

## What does this pull request do?

Adds aioredis instrumentation

## Related issues
closes #1080

2021-03-29 07:04 UTC, apmmachine commented
## :grey_exclamation: Build Aborted
  
  > The PR is not allowed to run in the CI yet
  


<!-- BUILD BADGES-->
> _the below badges are clickable and redirect to their specific view in the CI or DOCS_
[![Pipeline View](https://img.shields.io/badge/pipeline-pipeline%20-green)](https://apm-ci.elastic.co/blue/organizations/jenkins/apm-agent-python%2Fapm-agent-python-mbp%2FPR-1082/detail/PR-1082/1//pipeline) [![Test View](https://img.shields.io/badge/test-test-green)](https://apm-ci.elastic.co/blue/organizations/jenkins/apm-agent-python%2Fapm-agent-python-mbp%2FPR-1082/detail/PR-1082/1//tests) [![Changes](https://img.shields.io/badge/changes-changes-green)](https://apm-ci.elastic.co/blue/organizations/jenkins/apm-agent-python%2Fapm-agent-python-mbp%2FPR-1082/detail/PR-1082/1//changes) [![Artifacts](https://img.shields.io/badge/artifacts-artifacts-yellow)](https://apm-ci.elastic.co/blue/organizations/jenkins/apm-agent-python%2Fapm-agent-python-mbp%2FPR-1082/detail/PR-1082/1//artifacts) 

<!-- BUILD SUMMARY-->
<details><summary>Expand to view the summary</summary>
<p>

#### Build stats


* Build Cause: `Pull request #1082 opened`


* Reason: `The PR is not allowed to run in the CI yet`


* Start Time: 2021-03-29T07:01:20.972+0000


* Duration: 3 min 5 sec


* Commit: aa6d61a1cc5fcade54d7546a9981a50ca8dc4164




#### Trends :test_tube:


![Image of Build Times](https://apm-ci.elastic.co/job/apm-agent-python/job/apm-agent-python-mbp/job/PR-1082/buildTimeGraph/png)



</p>
</details>

<!-- TEST RESULTS IF ANY-->


<!-- STEPS ERRORS IF ANY -->









### Steps errors [![2](https://img.shields.io/badge/2%20-red)](https://apm-ci.elastic.co/blue/organizations/jenkins/apm-agent-python%2Fapm-agent-python-mbp%2FPR-1082/detail/PR-1082/1//pipeline)
  <details><summary>Expand to view the steps failures</summary>
  <p>


  
  
  
  
##### `Load a resource file from a shared library`
<ul>
<li>Took 0 min 0 sec . View more details on <a href="https://apm-ci.elastic.co//blue/rest/organizations/jenkins/pipelines/apm-agent-python/pipelines/apm-agent-python-mbp/pipelines/PR-1082/runs/1/steps/84/log/?start=0">here</a></li>
<li>Description: <code>approval-list/elastic/apm-agent-python.yml</code></l1>
</ul>
  
  
  
  
##### `Error signal`
<ul>
<li>Took 0 min 0 sec . View more details on <a href="https://apm-ci.elastic.co//blue/rest/organizations/jenkins/pipelines/apm-agent-python/pipelines/apm-agent-python-mbp/pipelines/PR-1082/runs/1/steps/87/log/?start=0">here</a></li>
<li>Description: <code>githubPrCheckApproved: The PR is not allowed to run in the CI yet. (Only users with write permissions can do so.)</code></l1>
</ul>
  
  </p>
  </details>



<!-- LOG OUTPUT-->
### Log output

<details><summary>Expand to view the last 100 lines of log output</summary>
<p>

```
[2021-03-29T07:03:55.858Z]  > git checkout -f aa6d61a1cc5fcade54d7546a9981a50ca8dc4164 # timeout=15
[2021-03-29T07:03:59.547Z] Commit message: "Add aioredis instrumentation"
[2021-03-29T07:03:59.547Z] First time build. Skipping changelog.
[2021-03-29T07:03:59.547Z] Cleaning workspace
[2021-03-29T07:03:59.628Z]  > git --version # timeout=10
[2021-03-29T07:03:59.633Z]  > git --version # 'git version 2.17.1'
[2021-03-29T07:03:59.640Z] fatal: bad object fbaca13d6c1a3541e236a4e1001d3af762ea4ccb
[2021-03-29T07:03:59.548Z]  > git rev-parse --verify HEAD # timeout=10
[2021-03-29T07:03:59.554Z] Resetting working tree
[2021-03-29T07:03:59.554Z]  > git reset --hard # timeout=10
[2021-03-29T07:03:59.584Z]  > git clean -fdx # timeout=10
[2021-03-29T07:04:00.449Z] Masking supported pattern matches of $JOB_GCS_BUCKET or $NOTIFY_TO
[2021-03-29T07:04:00.598Z] The timestamps step is unnecessary when timestamps are enabled for all Pipeline builds.
[2021-03-29T07:04:00.828Z] Timeout set to expire in 1 hr 0 min
[2021-03-29T07:04:01.556Z] [INFO] Number of builds to be searched 10
[2021-03-29T07:04:02.184Z] [INFO] 'shallow' is forced to be disabled when running on PullRequests
[2021-03-29T07:04:02.286Z] Running in /var/lib/jenkins/workspace/hon_apm-agent-python-mbp_PR-1082/src/github.com/elastic/apm-agent-python
[2021-03-29T07:04:02.469Z] [INFO] gitCheckout: Checkout SCM PR-1082 with default customisation from the Item.
[2021-03-29T07:04:02.637Z] [INFO] Override default checkout
[2021-03-29T07:04:02.783Z] Sleeping for 10 sec
[2021-03-29T07:04:12.820Z] The recommended git tool is: git
[2021-03-29T07:04:12.956Z] using credential f6c7695a-671e-4f4f-a331-acdce44ff9ba
[2021-03-29T07:04:12.973Z] Wiping out workspace first.
[2021-03-29T07:04:12.984Z] Cloning the remote Git repository
[2021-03-29T07:04:12.984Z] Using shallow clone with depth 3
[2021-03-29T07:04:12.984Z] Avoid fetching tags
[2021-03-29T07:04:12.999Z] Cloning repository git@github.com:elastic/apm-agent-python.git
[2021-03-29T07:04:13.029Z]  > git init /var/lib/jenkins/workspace/hon_apm-agent-python-mbp_PR-1082/src/github.com/elastic/apm-agent-python # timeout=10
[2021-03-29T07:04:13.035Z] Fetching upstream changes from git@github.com:elastic/apm-agent-python.git
[2021-03-29T07:04:13.035Z]  > git --version # timeout=10
[2021-03-29T07:04:13.045Z]  > git --version # 'git version 2.17.1'
[2021-03-29T07:04:13.046Z] using GIT_SSH to set credentials GitHub user @elasticmachine SSH key
[2021-03-29T07:04:13.052Z]  > git fetch --no-tags --progress -- git@github.com:elastic/apm-agent-python.git +refs/heads/*:refs/remotes/origin/* # timeout=15
[2021-03-29T07:04:14.361Z] Cleaning workspace
[2021-03-29T07:04:14.379Z] Using shallow fetch with depth 3
[2021-03-29T07:04:14.379Z] Pruning obsolete local branches
[2021-03-29T07:04:14.337Z]  > git config remote.origin.url git@github.com:elastic/apm-agent-python.git # timeout=10
[2021-03-29T07:04:14.341Z]  > git config --add remote.origin.fetch +refs/heads/*:refs/remotes/origin/* # timeout=10
[2021-03-29T07:04:14.351Z]  > git config remote.origin.url git@github.com:elastic/apm-agent-python.git # timeout=10
[2021-03-29T07:04:14.362Z]  > git rev-parse --verify HEAD # timeout=10
[2021-03-29T07:04:14.366Z] No valid HEAD. Skipping the resetting
[2021-03-29T07:04:14.367Z]  > git clean -fdx # timeout=10
[2021-03-29T07:04:14.380Z] Fetching upstream changes from git@github.com:elastic/apm-agent-python.git
[2021-03-29T07:04:14.380Z] using GIT_SSH to set credentials GitHub user @elasticmachine SSH key
[2021-03-29T07:04:14.384Z]  > git fetch --no-tags --progress --prune -- git@github.com:elastic/apm-agent-python.git +refs/pull/1082/head:refs/remotes/origin/PR-1082 +refs/heads/master:refs/remotes/origin/master # timeout=15
[2021-03-29T07:04:15.027Z] Merging remotes/origin/master commit 5ed034d3dc64a7966ac163a14a13d89d6d313fd4 into PR head commit aa6d61a1cc5fcade54d7546a9981a50ca8dc4164
[2021-03-29T07:04:15.133Z] Merge succeeded, producing aa6d61a1cc5fcade54d7546a9981a50ca8dc4164
[2021-03-29T07:04:15.134Z] Checking out Revision aa6d61a1cc5fcade54d7546a9981a50ca8dc4164 (PR-1082)
[2021-03-29T07:04:15.185Z] Commit message: "Add aioredis instrumentation"
[2021-03-29T07:04:15.185Z] Cleaning workspace
[2021-03-29T07:04:15.267Z]  > git --version # timeout=10
[2021-03-29T07:04:15.285Z]  > git --version # 'git version 2.17.1'
[2021-03-29T07:04:15.295Z] fatal: bad object fbaca13d6c1a3541e236a4e1001d3af762ea4ccb
[2021-03-29T07:04:15.028Z]  > git config core.sparsecheckout # timeout=10
[2021-03-29T07:04:15.033Z]  > git checkout -f aa6d61a1cc5fcade54d7546a9981a50ca8dc4164 # timeout=15
[2021-03-29T07:04:15.088Z]  > git remote # timeout=10
[2021-03-29T07:04:15.098Z]  > git config --get remote.origin.url # timeout=10
[2021-03-29T07:04:15.109Z] using GIT_SSH to set credentials GitHub user @elasticmachine SSH key
[2021-03-29T07:04:15.113Z]  > git merge 5ed034d3dc64a7966ac163a14a13d89d6d313fd4 # timeout=10
[2021-03-29T07:04:15.122Z]  > git rev-parse HEAD^{commit} # timeout=10
[2021-03-29T07:04:15.135Z]  > git config core.sparsecheckout # timeout=10
[2021-03-29T07:04:15.138Z]  > git checkout -f aa6d61a1cc5fcade54d7546a9981a50ca8dc4164 # timeout=15
[2021-03-29T07:04:15.186Z]  > git re [...]

2021-03-29 07:54 UTC, Sparkycz commented
I checked the failed jobs and I think these are beyond my changes. Please, anyone, check it out and help me to solve it.

2021-03-29 09:34 UTC, beniwohli reviewed
@Sparkycz awesome stuff, thanks a lot!

The original test failure was a problem on one of our Windows test machines, it went away when I restarted the test run.

The weird @houndci-bot failures seem to be related to https://github.com/houndci/hound/issues/1839. Nothing we can do about that right now...

I'll do a more in-depth review later this week.

2021-03-29 09:34 UTC, beniwohli commented on tests/instrumentation/asyncio_tests/aioredis_tests.py
> +    conn = await aioredis.create_redis_pool(f'redis://{_host}:{_port}')
The `black` code formatter fails on this

```suggestion
    conn = await aioredis.create_redis_pool(f"redis://{_host}:{_port}")
```

2021-03-29 12:51 UTC, ajay1mg commented
Thank you @Sparkycz, I checked your code and now wondering how fast you were in adding the support for this. Could you help me understand how you came up with this piece of code?

Going forward I would love to contribute to this since I may have other requirements with my APM integration

2021-04-06 08:25 UTC, beniwohli requested changes
@Sparkycz  Great work! I took the liberty to push some needed boilerplate code to ensure your tests are run in our CI test matrix.

I noticed that the maintainers of aioredis are getting ready to release version 2.0.0 of the library, which from the sound of it, changes more or less completely how the API of the library works. We'll probably need to adapt some things. Would you like to do that or should I take over that part?

2021-04-06 08:25 UTC, beniwohli commented on elasticapm/instrumentation/packages/asyncio/aioredis.py
> +        with capture_span(wrapped_name, span_type="db", span_subtype="redis", span_action="query", leaf=True) as span:
Can you use `async_capture_span` here instead? At the moment, it doesn't have a huge impact (all it really does is set the `sync` flag to `False` in the captured meta data), but in the future it will help us capturing additional asyncio data

2021-04-06 08:25 UTC, beniwohli commented on elasticapm/instrumentation/packages/asyncio/aioredis.py
> +        with capture_span(wrapped_name, span_type="db", span_subtype="redis", span_action="query", leaf=True) as span:
Also `async_capture_span` :)

2021-04-06 11:01 UTC, Sparkycz commented
> @Sparkycz Great work! I took the liberty to push some needed boilerplate code to ensure your tests are run in our CI test matrix.
> 
> I noticed that the maintainers of aioredis are getting ready to release version 2.0.0 of the library, which from the sound of it, changes more or less completely how the API of the library works. We'll probably need to adapt some things. Would you like to do that or should I take over that part?

Thanks for the boilerplate code I didn't know It's needed as well..

I'd wait for the stable release and I'll try doing that.. You imagine having two versions of the instrumentation https://github.com/elastic/apm-agent-python/pull/1082/commits/754731f7ab6832f42a5124e5fba1dd1d3b7ab226#diff-523e55d3048a9bdd660f01803427652e28fb5a0610ad41f9c6a98575e83ef67fR22 , don't you?

2021-04-19 06:47 UTC, Sparkycz commented
Hello @beniwohli, please, what is the PR waiting for? :-)

2021-04-24 05:34 UTC, Sparkycz commented
@basepi Could you unfreeze the PR please?

2021-04-27 12:43 UTC, beniwohli commented
@Sparkycz sorry about the wait here, we do have a lot of other work on our plate, so I didn't have a chance to merge the PR yet. I'll get it merged today and do a release soon.

2021-04-29 14:03 UTC, merged