fix "IndexError when "url" not found in args or kwargs"
elastic/apm-agent-python pull request #1890
Opened 2023-08-23 15:28 UTC by nbarbey

2023-08-23 17:39 UTC, basepi commented
@nbarbey I opened a PR against your PR, with a test and a little fix: https://github.com/nbarbey/apm-agent-python/pull/1

If you open PRs from a new branch instead of your `main` branch, it allows me to push changes directly to your PR, rather than having to open a new PR against your PR. Should make it easier next time. Thanks for the contribution!

2023-08-25 08:08 UTC, nbarbey commented
Ok I will be more careful next time about branch name.
I merge your PR in my fork. It seems it updated this PR automagically, nice !

2023-08-25 17:21 UTC, basepi commented
@elasticmachine, run elasticsearch-ci/docs

2023-08-25 17:21 UTC, basepi approved these changes

2023-08-28 20:34 UTC, basepi requested changes
One more change I missed to get the tests passing.

2023-08-28 20:34 UTC, basepi commented on elasticapm/instrumentation/packages/asyncio/aiohttp_client.py
> +            url = args[1]
```suggestion
        url = kwargs.get("url", kwargs.get("str_or_url", None))
        if url is None:
            url = args[1]
        url = str(url)
```

2023-09-05 17:40 UTC, basepi commented on elasticapm/instrumentation/packages/asyncio/aiohttp_client.py
> +            url = args[1]
@nbarbey Can you commit this suggestion so we can get this merged?

2023-09-06 18:55 UTC, basepi approved these changes

2023-09-06 19:38 UTC, basepi commented
@elasticmachine, run elasticsearch-ci/docs

2023-09-06 19:51 UTC, merged