Fix:Update starlette.asciidoc, incorrect middleware order
elastic/apm-agent-python pull request #1956
Opened 2024-01-23 15:06 UTC by mariocandela

## What does this pull request do?

The documentation contains an error, you need to put the APM middleware before BaseHTTPMiddleware.

2024-01-24 09:59 UTC, mariocandela commented
> I don't think this is correct:
> 
> > Using BaseHTTPMiddleware will prevent changes to [contextlib.ContextVar](https://docs.python.org/3/library/contextvars.html#contextvars.ContextVar)s from propagating upwards.
> 
> So, BaseHTTPMiddleware needs to be above (i.e. before) our middleware in the list so that we have an unbroken contextvar chain from the endpoint to our middleware.
> 
> Does this not match your experience?
> 
> Edit: see also the original issue: #1701
Yesterday, we integrated the APM agent across all our microservices, placing the agent's middleware as the last element. No data was reaching the APM server in this configuration. However, when we placed it as the first element, everything worked correctly. Could it be that one of our custom middlewares was invalidating the context variable?

Thanks for your time Colton :1st_place_medal:

2024-01-26 21:25 UTC, basepi commented
Are you passing in the middleware as a list or using the `add_middleware()` function repeatedly? I think that may be where the confusion is -- the original issue #1701 was using `add_middleware`, which appears to insert the middleware at the front of the list. Thus, the required order would be swapped based on how you're adding the middleware.

I think we need to expand this warning with examples of both.

2024-02-08 08:56 UTC, v1v commented
run docs-build

2024-02-13 00:41 UTC, basepi commented
@mariocandela Can you answer my question above?

2024-02-14 08:26 UTC, mariocandela commented
> @mariocandela Can you answer my question above?

Hi @basepi, sorry for the delay, we use middleware as a list.
Initially, we had the agent's middleware placed last, but data wasn't reaching the APM server in this setup. However, when we moved it to the first position, everything started working correctly.

I haven't had the chance to delve deeper into the issue yet. It's possible that our custom middleware, which utilizes dependency injection, could be causing the problem. I'll make sure to allocate some time to debug the APM and figure out what's going on with the contextvar.

Thanks for your time

2024-02-14 20:02 UTC, basepi commented
Alright, you've confirmed my suspicion. Our middleware must be first in the list if you're passing in a list of middleware, but last if you're adding each one manually with add_middleware. I'll add a commit to your PR clarifying that point.

2024-02-14 20:09 UTC, basepi requested changes
One change. Thanks again for talking through this with me!

2024-02-14 20:09 UTC, basepi commented on docs/starlette.asciidoc
>  https://www.starlette.io/middleware/#limitations[here].
```suggestion
WARNING: `BaseHTTPMiddleware` breaks `contextvar` propagation, as noted
https://www.starlette.io/middleware/#limitations[here]. This means the
ElasticAPM middleware must be above any `BaseHTTPMiddleware` in the final
middleware list. If you're calling `add_middleware` repeatedly, add the
ElasticAPM middleware last. If you're passing in a list of middleware,
ElasticAPM should be first on that list.
```

2024-02-15 22:51 UTC, mariocandela commented
> One change. Thanks again for talking through this with me!

thank you for your time!

2024-02-21 04:04 UTC, basepi approved these changes

2024-02-21 04:05 UTC, basepi commented
run docs-build

2024-02-21 22:17 UTC, merged